# OpenSASE Peering Engine - IXP Port Module
# Provisions ports at Internet Exchange Points

variable "ixp_config" {
  description = "IXP port configuration"
  type = object({
    ixp_id       = number
    ixp_name     = string
    pop_name     = string
    speed_mbps   = number
    ipv4_address = optional(string)
    ipv6_address = optional(string)
    vlan_id      = number
  })
}

variable "environment" {
  type    = string
  default = "production"
}

variable "provider_type" {
  description = "Underlying provider: equinix, megaport, etc."
  type        = string
  default     = "equinix"
}

variable "opensase_asn" {
  type    = number
  default = 65100
}

# ===========================================
# Locals
# ===========================================

locals {
  # IXP configuration by ID
  ixp_configs = {
    # DE-CIX Frankfurt
    26 = {
      vlan_range = [100, 199]
      route_server_v4 = ["80.81.192.157", "80.81.192.158"]
      route_server_v6 = ["2001:7f8::6e28:0:1", "2001:7f8::6e28:0:2"]
      rs_asn = 6695
      prefix_v4 = "80.81.192.0/22"
      prefix_v6 = "2001:7f8::/32"
    }
    
    # AMS-IX
    18 = {
      vlan_range = [300, 399]
      route_server_v4 = ["80.249.208.31", "80.249.208.32"]
      route_server_v6 = ["2001:7f8:1::a502:6695:1", "2001:7f8:1::a502:6695:2"]
      rs_asn = 6777
      prefix_v4 = "80.249.208.0/21"
      prefix_v6 = "2001:7f8:1::/48"
    }
    
    # LINX LON1
    10 = {
      vlan_range = [200, 299]
      route_server_v4 = ["195.66.224.1", "195.66.224.2"]
      route_server_v6 = ["2001:7f8:4::1", "2001:7f8:4::2"]
      rs_asn = 8714
      prefix_v4 = "195.66.224.0/21"
      prefix_v6 = "2001:7f8:4::/48"
    }
    
    # Equinix Ashburn
    171 = {
      vlan_range = [400, 499]
      route_server_v4 = ["206.126.236.1"]
      route_server_v6 = ["2001:504:0:2::1"]
      rs_asn = 19754
      prefix_v4 = "206.126.236.0/22"
      prefix_v6 = "2001:504:0:2::/48"
    }
  }
  
  ixp_data = lookup(local.ixp_configs, var.ixp_config.ixp_id, {
    vlan_range = [100, 199]
    route_server_v4 = []
    route_server_v6 = []
    rs_asn = 0
    prefix_v4 = ""
    prefix_v6 = ""
  })
  
  # Cost estimation
  port_monthly_cost = (
    var.ixp_config.speed_mbps == 1000 ? 500 :
    var.ixp_config.speed_mbps == 10000 ? 2000 :
    var.ixp_config.speed_mbps == 100000 ? 8000 : 5000
  )
}

# ===========================================
# VPP Configuration
# ===========================================

resource "local_file" "vpp_config" {
  filename = "${path.module}/generated/${var.ixp_config.pop_name}-${var.ixp_config.ixp_id}-vpp.conf"
  
  content = <<-EOF
# VPP IXP Port Configuration
# IXP: ${var.ixp_config.ixp_name}
# PoP: ${var.ixp_config.pop_name}

create sub-interface TenGigabitEthernet0/0/0 ${var.ixp_config.vlan_id}
set interface state TenGigabitEthernet0/0/0.${var.ixp_config.vlan_id} up
set interface mtu 9000 TenGigabitEthernet0/0/0.${var.ixp_config.vlan_id}

%{ if var.ixp_config.ipv4_address != null ~}
set interface ip address TenGigabitEthernet0/0/0.${var.ixp_config.vlan_id} ${var.ixp_config.ipv4_address}/24
%{ endif ~}

%{ if var.ixp_config.ipv6_address != null ~}
set interface ip address TenGigabitEthernet0/0/0.${var.ixp_config.vlan_id} ${var.ixp_config.ipv6_address}/64
%{ endif ~}

comment { OSPE IXP Port: ${var.ixp_config.ixp_name} }
EOF
}

# ===========================================
# BIRD Configuration
# ===========================================

resource "local_file" "bird_config" {
  filename = "${path.module}/generated/${var.ixp_config.pop_name}-${var.ixp_config.ixp_id}-bird.conf"
  
  content = <<-EOF
# BIRD BGP Configuration for ${var.ixp_config.ixp_name}
# Generated by OpenSASE Peering Engine

define IXP_${upper(replace(var.ixp_config.ixp_name, "-", "_"))}_LOCAL_IP = ${coalesce(var.ixp_config.ipv4_address, "0.0.0.0")};

# Route Server Sessions
%{ for i, rs in local.ixp_data.route_server_v4 ~}
protocol bgp rs_${var.ixp_config.ixp_id}_${i + 1} {
    local as ${var.opensase_asn};
    neighbor ${rs} as ${local.ixp_data.rs_asn};
    source address IXP_${upper(replace(var.ixp_config.ixp_name, "-", "_"))}_LOCAL_IP;
    description "Route Server ${i + 1} @ ${var.ixp_config.ixp_name}";
    
    ipv4 {
        import filter ixp_import;
        export filter ixp_export;
        import limit 200000 action restart;
    };
    
    graceful restart on;
}

%{ endfor ~}

# Filters
filter ixp_import {
    # Reject bogons
    if net ~ [ 0.0.0.0/8+, 10.0.0.0/8+, 172.16.0.0/12+, 192.168.0.0/16+ ] then reject;
    
    # Reject too specific
    if net.len > 24 then reject;
    
    # Reject too short AS paths (likely leaks)
    if bgp_path.len > 64 then reject;
    
    # Accept and tag
    bgp_community.add((${var.opensase_asn}, 100));  # IXP learned
    bgp_local_pref = 150;
    accept;
}

filter ixp_export {
    # Only export our prefixes
    if source = RTS_STATIC then accept;
    if source = RTS_BGP && bgp_community ~ (${var.opensase_asn}, 300) then accept;
    reject;
}
EOF
}

# ===========================================
# Ansible Inventory Entry
# ===========================================

resource "local_file" "ansible_vars" {
  filename = "${path.module}/generated/${var.ixp_config.pop_name}-${var.ixp_config.ixp_id}-vars.yml"
  
  content = yamlencode({
    ixp_port = {
      ixp_id       = var.ixp_config.ixp_id
      ixp_name     = var.ixp_config.ixp_name
      pop_name     = var.ixp_config.pop_name
      speed_mbps   = var.ixp_config.speed_mbps
      vlan_id      = var.ixp_config.vlan_id
      ipv4_address = var.ixp_config.ipv4_address
      ipv6_address = var.ixp_config.ipv6_address
      
      route_servers = {
        v4  = local.ixp_data.route_server_v4
        v6  = local.ixp_data.route_server_v6
        asn = local.ixp_data.rs_asn
      }
    }
  })
}

# ===========================================
# Outputs
# ===========================================

output "port_info" {
  value = {
    ixp_id       = var.ixp_config.ixp_id
    ixp_name     = var.ixp_config.ixp_name
    pop_name     = var.ixp_config.pop_name
    speed_mbps   = var.ixp_config.speed_mbps
    vlan_id      = var.ixp_config.vlan_id
    ipv4_address = var.ixp_config.ipv4_address
    ipv6_address = var.ixp_config.ipv6_address
    monthly_cost = local.port_monthly_cost
  }
}

output "route_servers" {
  value = {
    v4  = local.ixp_data.route_server_v4
    v6  = local.ixp_data.route_server_v6
    asn = local.ixp_data.rs_asn
  }
}

output "config_files" {
  value = {
    vpp    = local_file.vpp_config.filename
    bird   = local_file.bird_config.filename
    ansible = local_file.ansible_vars.filename
  }
}
