#!/bin/bash
# Add New Branch Script
# Provisions a new branch site in under 10 minutes

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Usage
usage() {
    cat << EOF
Usage: $0 <branch-name> <branch-id>

Add a new branch site to the OpenSASE-Lab SD-WAN.

Arguments:
  branch-name   Name for the new branch (e.g., branch-d, remote-office-1)
  branch-id     Numeric ID (4-254) for IP addressing (e.g., 4 → 10.204.0.0/24)

Example:
  $0 branch-d 4

This will:
  1. Generate edge configuration files
  2. Create Docker Compose service definition
  3. Request device token from controller
  4. Output instructions for container startup

EOF
    exit 1
}

# Validate inputs
validate_inputs() {
    local name="$1"
    local id="$2"
    
    if [ -z "$name" ] || [ -z "$id" ]; then
        usage
    fi
    
    if ! [[ "$id" =~ ^[0-9]+$ ]] || [ "$id" -lt 4 ] || [ "$id" -gt 254 ]; then
        log_error "Branch ID must be a number between 4 and 254"
        exit 1
    fi
    
    if [ -d "$PROJECT_DIR/docker/flexiwan-edge/$name" ]; then
        log_error "Branch '$name' already exists"
        exit 1
    fi
}

# Generate edge configuration
generate_config() {
    local name="$1"
    local id="$2"
    
    local config_dir="$PROJECT_DIR/docker/flexiwan-edge/$name"
    mkdir -p "$config_dir"
    
    log_info "Generating configuration for $name..."
    
    cat > "$config_dir/device.conf" << EOF
# FlexiWAN Edge Configuration - ${name}
# Generated by add-branch.sh on $(date)

[device]
name = ${name}
description = OpenSASE Lab Edge - ${name}

[controller]
url = https://flexiwan-controller:4433
verify_ssl = false

# ============================================
# Interface Configuration (Dual WAN)
# ============================================

[interface.wan1]
name = eth0
type = wan
ip = 10.200.0.${id}1
gateway = 10.200.0.1
metric = 100
enabled = true

[interface.wan2]
name = eth1
type = wan
ip = 10.200.0.${id}2
gateway = 10.200.0.1
metric = 200
enabled = true

[interface.lan]
name = eth2
type = lan
ip = 10.20${id}.0.1
subnet = 10.20${id}.0.0/24
enabled = true

# ============================================
# VLAN Configuration (VRF/Segmentation)
# ============================================

[vlan.corp]
id = 100
interface = eth2
segment = 1
description = Corporate network segment

[vlan.guest]
id = 200
interface = eth2
segment = 2
description = Guest network segment

# ============================================
# Tunnel Configuration
# ============================================

[tunnel.to-pop]
type = wireguard
peer = pop-gateway
interface = wan1
fallback_interface = wan2
keepalive = 25
mtu = 1420
EOF

    log_info "Configuration created: $config_dir/device.conf"
}

# Generate Docker Compose fragment
generate_compose_fragment() {
    local name="$1"
    local id="$2"
    
    local fragment_file="$PROJECT_DIR/docker/flexiwan-edge/$name/docker-compose.yml"
    
    log_info "Generating Docker Compose fragment..."
    
    cat > "$fragment_file" << EOF
# Docker Compose fragment for ${name}
# Add this to the main docker-compose.yml services section

  ${name}:
    image: flexiwan/flexiwan-router:latest
    container_name: ${name}
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      FLEXIWAN_CONTROLLER: https://flexiwan-controller:4433
      DEVICE_TOKEN: \${${name^^}_TOKEN:-auto}
      DEVICE_NAME: ${name}
    volumes:
      - ./docker/flexiwan-edge/${name}:/etc/flexiwan:ro
    networks:
      pop-net:
        ipv4_address: 10.200.0.${id}1
      ${name}-net:
        ipv4_address: 10.20${id}.0.1
    depends_on:
      - flexiwan-controller

# Also add this network definition:
#  ${name}-net:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.20${id}.0.0/24
EOF

    log_info "Docker Compose fragment created: $fragment_file"
}

# Request device token
request_token() {
    local name="$1"
    
    log_info "Requesting device token from controller..."
    
    # Load existing token file
    local token_file="$PROJECT_DIR/.device-tokens"
    
    # Check if controller is running
    if ! curl -sf "http://localhost:3000/api/health" > /dev/null 2>&1; then
        log_warn "Controller not running. Token will be requested on first edge startup."
        echo "${name}=AUTO_ENROLL" >> "$token_file"
        return
    fi
    
    # Attempt to get token via API
    local admin_token=$(curl -sf -X POST "http://localhost:3000/api/auth/login" \
        -H "Content-Type: application/json" \
        -d '{"email": "'${FLEXIWAN_ADMIN_EMAIL:-admin@opensase.lab}'", "password": "'${FLEXIWAN_ADMIN_PASSWORD:-changeme_flexiwan}'"}' \
        | jq -r '.token // empty')
    
    if [ -n "$admin_token" ]; then
        local device_token=$(curl -sf -X POST "http://localhost:3000/api/devices/tokens" \
            -H "Authorization: Bearer ${admin_token}" \
            -H "Content-Type: application/json" \
            -d '{"name": "'$name'"}' \
            | jq -r '.token // empty')
        
        if [ -n "$device_token" ]; then
            echo "${name}=${device_token}" >> "$token_file"
            log_info "Device token saved to $token_file"
            return
        fi
    fi
    
    log_warn "Could not get token automatically. Use FlexiWAN UI to generate token."
    echo "${name}=MANUAL_ENROLL" >> "$token_file"
}

# Print next steps
print_next_steps() {
    local name="$1"
    local id="$2"
    
    echo ""
    echo -e "${CYAN}========================================${NC}"
    echo -e "${CYAN}  Branch '$name' Created Successfully!${NC}"
    echo -e "${CYAN}========================================${NC}"
    echo ""
    echo "Generated files:"
    echo "  - docker/flexiwan-edge/$name/device.conf"
    echo "  - docker/flexiwan-edge/$name/docker-compose.yml"
    echo ""
    echo "Network details:"
    echo "  - LAN Subnet: 10.20${id}.0.0/24"
    echo "  - WAN1 IP: 10.200.0.${id}1"
    echo "  - WAN2 IP: 10.200.0.${id}2"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo ""
    echo "1. Add the service to docker-compose.yml:"
    echo "   cat docker/flexiwan-edge/$name/docker-compose.yml"
    echo ""
    echo "2. Add the network to docker-compose.yml networks section:"
    echo "   ${name}-net:"
    echo "     driver: bridge"
    echo "     ipam:"
    echo "       config:"
    echo "         - subnet: 10.20${id}.0.0/24"
    echo ""
    echo "3. Add environment variable to .env:"
    echo "   ${name^^}_TOKEN=<token-from-flexiwan-ui>"
    echo ""
    echo "4. Start the new branch:"
    echo "   docker compose up -d $name"
    echo ""
    echo "5. Verify enrollment in FlexiWAN UI:"
    echo "   http://localhost:3000"
    echo ""
    echo -e "${GREEN}Total time: ~5 minutes${NC}"
}

# Main
main() {
    local name="$1"
    local id="$2"
    
    echo -e "${CYAN}========================================${NC}"
    echo -e "${CYAN}  Add New Branch Site${NC}"
    echo -e "${CYAN}========================================${NC}"
    echo ""
    
    validate_inputs "$name" "$id"
    generate_config "$name" "$id"
    generate_compose_fragment "$name" "$id"
    request_token "$name"
    print_next_steps "$name" "$id"
}

main "$@"
