#!/bin/bash
# FlexiWAN Edge Bootstrap Script
# Configures edge devices with dual WAN, VRF, and tunnel settings

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Load environment
if [ -f "$PROJECT_DIR/.env" ]; then
    source "$PROJECT_DIR/.env"
fi

# Configuration
CONTROLLER_URL="${FLEXIWAN_CONTROLLER_URL:-https://flexiwan-controller:4433}"
EDGES_DIR="$PROJECT_DIR/docker/flexiwan-edge"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

# Edge configurations with dual WAN
declare -A EDGE_CONFIG
EDGE_CONFIG[branch-a]="
name=branch-a
lan_subnet=10.201.0.0/24
lan_ip=10.201.0.1
wan1_ip=10.200.0.11
wan2_ip=10.200.0.21
corp_vlan=100
guest_vlan=200
"

EDGE_CONFIG[branch-b]="
name=branch-b
lan_subnet=10.202.0.0/24
lan_ip=10.202.0.1
wan1_ip=10.200.0.12
wan2_ip=10.200.0.22
corp_vlan=100
guest_vlan=200
"

EDGE_CONFIG[branch-c]="
name=branch-c
lan_subnet=10.203.0.0/24
lan_ip=10.203.0.1
wan1_ip=10.200.0.13
wan2_ip=10.200.0.23
corp_vlan=100
guest_vlan=200
"

# Generate edge configuration file
generate_edge_config() {
    local branch="$1"
    local config_dir="$EDGES_DIR/$branch"
    
    mkdir -p "$config_dir"
    
    # Parse config
    eval "${EDGE_CONFIG[$branch]}"
    
    # Load device token if available
    local device_token=""
    if [ -f "$PROJECT_DIR/.device-tokens" ]; then
        device_token=$(grep "^${branch}=" "$PROJECT_DIR/.device-tokens" | cut -d= -f2)
    fi
    
    log_info "Generating configuration for $branch..."
    
    # Main device configuration
    cat > "$config_dir/device.conf" << EOF
# FlexiWAN Edge Configuration - ${name}
# Generated by edge-bootstrap.sh

[device]
name = ${name}
description = OpenSASE Lab Edge - ${name}
token = ${device_token:-AUTO_REGISTER}

[controller]
url = ${CONTROLLER_URL}
verify_ssl = false

# ============================================
# Interface Configuration (Dual WAN)
# ============================================

[interface.wan1]
name = eth0
type = wan
ip = ${wan1_ip}
gateway = 10.200.0.1
metric = 100
mtu = 1500
enabled = true

[interface.wan2]
name = eth1
type = wan
ip = ${wan2_ip}
gateway = 10.200.0.1
metric = 200
mtu = 1500
enabled = true

[interface.lan]
name = eth2
type = lan
ip = ${lan_ip}
subnet = ${lan_subnet}
enabled = true

# ============================================
# VLAN Configuration (VRF/Segmentation)
# ============================================

[vlan.corp]
id = ${corp_vlan}
interface = eth2
segment = 1
description = Corporate network segment

[vlan.guest]
id = ${guest_vlan}
interface = eth2
segment = 2
description = Guest network segment

# ============================================
# Tunnel Configuration
# ============================================

[tunnel.to-pop]
type = wireguard
peer = pop-gateway
interface = wan1
fallback_interface = wan2
keepalive = 25
mtu = 1420

# ============================================
# Routing
# ============================================

[routing]
# Corp segment routes via PoP
corp_default_route = tunnel.to-pop

# Guest segment uses local breakout
guest_default_route = wan1
guest_failover = wan2

# ============================================
# Path Selection & QoS
# ============================================

[path-selection]
enabled = true
probe_interval = 5
failover_threshold_ms = 100
failover_packet_loss_pct = 5

[qos]
enabled = true
corp_priority = high
guest_priority = low
EOF

    # WireGuard configuration
    cat > "$config_dir/wg0.conf" << EOF
# WireGuard tunnel to PoP
# Keys will be generated on first start

[Interface]
Address = 10.210.${branch: -1}.1/24
ListenPort = 51820
# PrivateKey = <generated>

[Peer]
# PoP Gateway
PublicKey = <pop-public-key>
AllowedIPs = 10.200.0.0/24, 10.210.0.0/16
Endpoint = 10.200.0.1:51820
PersistentKeepalive = 25
EOF

    log_info "Configuration generated for $branch"
}

# Generate all edge configurations
generate_all_configs() {
    log_info "Generating edge configurations..."
    
    for branch in branch-a branch-b branch-c; do
        generate_edge_config "$branch"
    done
    
    log_info "All edge configurations generated"
}

# Create PoP gateway configuration
generate_pop_config() {
    local config_dir="$EDGES_DIR/pop-gateway"
    mkdir -p "$config_dir"
    
    log_info "Generating PoP gateway configuration..."
    
    cat > "$config_dir/device.conf" << EOF
# FlexiWAN PoP Gateway Configuration
# Hub for all branch tunnels

[device]
name = pop-gateway
description = OpenSASE Lab Security PoP
role = hub

[controller]
url = ${CONTROLLER_URL}
verify_ssl = false

# ============================================
# WAN Interface (Internet)
# ============================================

[interface.wan]
name = eth0
type = wan
dhcp = false
ip = 10.200.0.1
gateway = <external-gateway>
enabled = true

# ============================================
# Tunnel Endpoints
# ============================================

[tunnel.branch-a]
type = wireguard
peer = branch-a
listen_port = 51821

[tunnel.branch-b]
type = wireguard
peer = branch-b
listen_port = 51822

[tunnel.branch-c]
type = wireguard
peer = branch-c
listen_port = 51823

# ============================================
# Segment Routing
# ============================================

[routing.corp]
# Corp traffic gets inspected by Suricata
next_hop = security-pop

[routing.guest]
# Guest breakout at branch (no hub routing needed)
action = drop

# ============================================
# Security Integration
# ============================================

[security]
suricata_enabled = true
suricata_host = security-pop
log_forwarding = wazuh-manager
EOF

    log_info "PoP gateway configuration generated"
}

# Main
main() {
    echo "=================================="
    echo "FlexiWAN Edge Bootstrap"
    echo "=================================="
    
    generate_all_configs
    generate_pop_config
    
    echo ""
    log_info "Edge bootstrap complete!"
    echo ""
    echo "Generated configurations:"
    echo "  - $EDGES_DIR/branch-a/device.conf"
    echo "  - $EDGES_DIR/branch-b/device.conf"
    echo "  - $EDGES_DIR/branch-c/device.conf"
    echo "  - $EDGES_DIR/pop-gateway/device.conf"
    echo ""
    echo "Next steps:"
    echo "  1. Review configurations in $EDGES_DIR/"
    echo "  2. Start edges with: docker compose up -d branch-a branch-b branch-c"
    echo "  3. Monitor enrollment in FlexiWAN UI"
    echo ""
}

main "$@"
