# OBMO Ansible Inventory
# Generated by Terraform for ${pop_name}

all:
  children:
    ${pop_name}:
      hosts:
%{ for server in servers }
        ${server.name}:
          ansible_host: ${server.public_ip}
%{ if server.private_ip != "" }
          private_ip: ${server.private_ip}
%{ endif }
          is_primary: ${server.is_primary}
%{ endfor }
      vars:
        ansible_user: ${ssh_user}
        ansible_ssh_private_key_file: ${ssh_key_path}
        ansible_become: true
        
        # PoP Configuration
        pop_name: ${pop_name}
        provider: ${provider_type}
        environment: ${environment}
        
        # Network Configuration
        nic_type: ${nic_type}
        nic_speed: ${nic_speed}
        
        # FlexiWAN
        controller_url: ${flexiwan_url}
        activation_key: ${flexiwan_token}
        
        # BGP Configuration
        enable_bgp: ${enable_bgp}
%{ if enable_bgp }
        bgp_asn: ${bgp_asn}
%{ if length(anycast_prefixes) > 0 }
        anycast_prefixes:
%{ for prefix in anycast_prefixes }
          - ${prefix}
%{ endfor }
%{ endif }
%{ endif }
        
        # VPP Configuration
        vpp_worker_cores: ${vpp_config.worker_cores}
        vpp_rx_queues: ${vpp_config.rx_queues}
        vpp_tx_queues: ${vpp_config.tx_queues}
        vpp_rx_desc: ${vpp_config.rx_desc}
        vpp_tx_desc: ${vpp_config.tx_desc}
        vpp_buffers: ${vpp_config.buffers}
        hugepages_gb: ${vpp_config.hugepages_gb}
