#!/bin/bash
# OpenSASE PoP Bootstrap Script
# Auto-generated by Terraform

set -euo pipefail

exec > >(tee /var/log/opensase-bootstrap.log) 2>&1

echo "============================================"
echo "  OpenSASE PoP Bootstrap"
echo "  PoP: ${pop_name}"
echo "  Environment: ${environment}"
echo "  Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "============================================"

# ===========================================
# System Updates
# ===========================================

echo "[1/7] Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade -y

# ===========================================
# Install Prerequisites
# ===========================================

echo "[2/7] Installing prerequisites..."
apt-get install -y \
    curl \
    wget \
    git \
    jq \
    htop \
    iotop \
    net-tools \
    dnsutils \
    tcpdump \
    python3 \
    python3-pip \
    ansible

# ===========================================
# Configure System for VPP
# ===========================================

echo "[3/7] Configuring system for high-performance networking..."

# Hugepages
echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
cat >> /etc/sysctl.conf << 'EOF'
# OpenSASE VPP Tuning
vm.nr_hugepages = 1024
vm.hugetlb_shm_group = 0
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.core.netdev_max_backlog = 250000
net.ipv4.tcp_rmem = 4096 87380 134217728
net.ipv4.tcp_wmem = 4096 65536 134217728
net.ipv4.ip_forward = 1
EOF
sysctl -p

# Mount hugetlbfs
mkdir -p /dev/hugepages
mount -t hugetlbfs nodev /dev/hugepages || true
echo "hugetlbfs /dev/hugepages hugetlbfs defaults 0 0" >> /etc/fstab

# ===========================================
# Install VPP
# ===========================================

echo "[4/7] Installing VPP..."
curl -sL https://packagecloud.io/install/repositories/fdio/release/script.deb.sh | bash
apt-get install -y \
    vpp \
    vpp-plugin-core \
    vpp-plugin-dpdk \
    vpp-plugin-wireguard \
    vpp-plugin-nat \
    vpp-plugin-acl

# Configure VPP
mkdir -p /etc/vpp
cat > /etc/vpp/startup.conf << 'EOF'
unix {
    nodaemon
    cli-listen /run/vpp/cli.sock
    log /var/log/vpp/vpp.log
    full-coredump
    gid vpp
}

api-segment {
    gid vpp
}

socksvr {
    default
}

cpu {
    main-core 0
    corelist-workers 1-3
    scheduler-policy fifo
    scheduler-priority 50
}

dpdk {
    dev default {
        num-rx-queues 2
        num-tx-queues 2
    }
    uio-driver vfio-pci
    socket-mem 1024
    num-mbufs 131072
}

plugins {
    plugin default { enable }
    plugin dpdk_plugin.so { enable }
    plugin wireguard_plugin.so { enable }
    plugin nat_plugin.so { enable }
    plugin acl_plugin.so { enable }
}

buffers {
    buffers-per-numa 128000
    default data-size 2048
}

statseg {
    socket-name /var/run/vpp/stats.sock
    size 128M
}
EOF

systemctl enable vpp

# ===========================================
# Install flexiEdge
# ===========================================

echo "[5/7] Installing flexiEdge..."
curl -sL https://deb.flexiwan.com/setup | bash
apt-get install -y flexiwan-router

# Configure flexiEdge
mkdir -p /etc/flexiwan
cat > /etc/flexiwan/agent.conf << EOF
{
    "deviceName": "${pop_name}",
    "dataPlane": "vpp",
    "vppSocketPath": "/run/vpp/cli.sock",
    "managementUrl": "${flexiwan_url}",
    "token": "${flexiwan_token}",
    "logLevel": "info",
    "telemetryInterval": 30,
    "features": {
        "sdwan": true,
        "firewall": true,
        "nat": true,
        "qos": true,
        "wireguard": true
    }
}
EOF

systemctl enable flexiwan

# ===========================================
# Install Suricata
# ===========================================

echo "[6/7] Installing Suricata..."
add-apt-repository -y ppa:oisf/suricata-stable
apt-get update
apt-get install -y suricata suricata-update

# Update Suricata rules
suricata-update

# Configure Suricata
cat > /etc/suricata/suricata.yaml.local << 'EOF'
%YAML 1.1
---
af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    ring-size: 200000

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert
        - tls
        - dns
        - http
        - flow
EOF

systemctl enable suricata

# ===========================================
# Install Monitoring
# ===========================================

echo "[7/7] Installing monitoring agents..."

# Node Exporter
wget -q https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
tar xzf node_exporter-1.7.0.linux-amd64.tar.gz
mv node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/
rm -rf node_exporter-*

cat > /etc/systemd/system/node_exporter.service << 'EOF'
[Unit]
Description=Node Exporter
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/node_exporter
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl enable node_exporter
systemctl start node_exporter

# ===========================================
# Start Services
# ===========================================

echo "Starting OpenSASE services..."
systemctl start vpp
sleep 3
systemctl start flexiwan
systemctl start suricata

# ===========================================
# Health Check Endpoint
# ===========================================

cat > /opt/opensase-health.py << 'EOF'
#!/usr/bin/env python3
import http.server
import json
import subprocess
import socketserver

class HealthHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/health':
            health = self.check_health()
            self.send_response(200 if health['status'] == 'healthy' else 503)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps(health).encode())
        else:
            self.send_response(404)
            self.end_headers()
    
    def check_health(self):
        services = {
            'vpp': self.check_service('vpp'),
            'flexiwan': self.check_service('flexiwan'),
            'suricata': self.check_service('suricata')
        }
        return {
            'status': 'healthy' if all(services.values()) else 'unhealthy',
            'services': services,
            'pop': '${pop_name}'
        }
    
    def check_service(self, name):
        result = subprocess.run(['systemctl', 'is-active', name], capture_output=True)
        return result.returncode == 0

if __name__ == '__main__':
    with socketserver.TCPServer(('', 8080), HealthHandler) as httpd:
        httpd.serve_forever()
EOF

chmod +x /opt/opensase-health.py

cat > /etc/systemd/system/opensase-health.service << 'EOF'
[Unit]
Description=OpenSASE Health Check
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/opensase-health.py
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl enable opensase-health
systemctl start opensase-health

# ===========================================
# Complete
# ===========================================

echo "============================================"
echo "  OpenSASE PoP Bootstrap Complete!"
echo "  PoP: ${pop_name}"
echo ""
echo "  Services:"
echo "    VPP:      $(systemctl is-active vpp)"
echo "    flexiWAN: $(systemctl is-active flexiwan)"
echo "    Suricata: $(systemctl is-active suricata)"
echo ""
echo "  Health: http://localhost:8080/health"
echo "============================================"
